from typing import List, Protocol

from src.glue_settings.glue_settings_data import GlueSettings
from src.glue_settings.glue_type import GlueType


class IGlueSettingsRepository(Protocol):
    def load(self) -> GlueSettings: ...
    def save(self, settings: GlueSettings) -> None: ...


class IGlueTypeRepository(Protocol):
    def load(self) -> List[GlueType]: ...
    def add(self, name: str, description: str) -> GlueType: ...
    def update(self, id: str, name: str, description: str) -> GlueType: ...
    def remove(self, id: str) -> None: ...
