from typing import Protocol

from src.plugins.glue_settings.glue_settings_data import GlueSettings
from src.plugins.glue_settings.glue_type import GlueType


class GlueSettingsService(Protocol):
    """Unified service interface for glue settings and glue types."""

    def load_settings(self) -> GlueSettings: ...
    def save_settings(self, settings: GlueSettings) -> None: ...

    def load_glue_types(self) -> list[GlueType]: ...
    def add_glue_type(self, name: str, description: str) -> GlueType: ...
    def update_glue_type(self, id_: str, name: str, description: str) -> GlueType: ...
    def remove_glue_type(self, id_: str) -> None: ...

